#!/data/data/com.termux/files/usr/bin/bash

# vars
tps_version="v0.05"
users=$(whoami)
work_path=$PREFIX/lib/tpaxs
tool_path=$PREFIX/lib/tpaxs/tools
LANGUAGE=$(cat $work_path/config/lang)

R=$(printf '\033[31m')
G=$(printf '\033[32m')
Y=$(printf '\033[33m')
B=$(printf '\033[34m')
P=$(printf '\033[35m')
C=$(printf '\033[36m')
RES=$(printf '\033[0m')
BOLD=$(printf '\033[1m')

# out function
apt_echo(){
  echo ${R}apt ${B}install ${Y}$1${RES}
  apt install -y $1 
}
tps_err(){
  datas=$(date "+%H:%M:%S")
  echo "${R}${BOLD}[ERR]${RES}${C} [${datas}]${RES}: $1"
}
tps_warm(){
  datas=$(date "+%H:%M:%S")
  echo "${Y}${BOLD}[WRM]${RES}${C} [${datas}]${RES}: $1"
}
tps_info(){
  datas=$(date "+%H:%M:%S")
  echo "${B}${BOLD}[IFO]${RES}${C} [${datas}]${RES}: $1"
}
tps_done(){
  datas=$(date "+%H:%M:%S")
  echo "${G}${BOLD}[OK ]${RES}${C} [${datas}]${RES}: $1"
}

# conf Read
# iniread
iniRead(){
  value=$(awk -F "=" '/\['${2}'\]/{a=1}a==1&&$1~/'${3}'/{print $2;exit}' $1)
  echo $value
}

iniWrite(){
  awk -F "=" '/\['${2}'\]/{a=1} (a==1 && "'${3}'"==$1){gsub($2,"'${4}'");a=0} {print $0}' ${1} 1<>${1}
}

